#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$inBamFiles" ]
then
  inBamFiles="$1"
fi
if [ -z "$genomeFastaFile" ]
then
  genomeFastaFile=$2
fi
if [ -z "$dbSnpVcfFile" ]
then
  dbSnpVcfFile=$3
fi
if [ -z "$glm" ]
then
  glm=$4
fi
if [ -z "$numThreads" ]
then
  numThreads=$5
fi
if [ -z "$outFile" ]
then
  outFile=$6
fi

source scripts/exome/paths

echo Unified genotype
java -Xmx24g -jar $gatkDir/GenomeAnalysisTK.jar \
  `ls $inBamFiles | xargs -L 1 echo -I \\` \
  -R $genomeFastaFile \
  -T UnifiedGenotyper \
  -out_mode EMIT_VARIANTS_ONLY \
  --dbsnp $dbSnpVcfFile \
  -dcov 500 \
  --min_base_quality_score 20 \
  -glm $glm \
  --num_threads $numThreads \
  -o $outFile

#  --standard_min_confidence_threshold_for_calling 20 \
#  --standard_min_confidence_threshold_for_emitting 20 \
