#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi
if [ -z "$inBamFiles" ]
then
  inBamFiles="$1"
fi
if [ -z "$genomeFastaFile" ]
then
  genomeFastaFile="$2"
fi
if [ -z "$knownVcfFile" ]
then
  knownVcfFile="$3"
fi
if [ -z "$outIntervalsFile" ]
then
  outIntervalsFile="$4"
fi

source scripts/exome/paths

echo Creating realigned target file
java -Xmx16g -jar $gatkDir/GenomeAnalysisTK.jar \
  -T RealignerTargetCreator \
  -R $genomeFastaFile \
  `ls $inBamFiles | xargs -L 1 echo -I \\` \
  --known $knownVcfFile \
  -o $outIntervalsFile
