#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$inVcfFile" ]
then
  inVcfFile=$1
fi
if [ -z "$genomeFastaFile" ]
then
  genomeFastaFile=$2
fi
if [ -z "$outVcfFile" ]
then
  outVcfFile=$3
fi

source scripts/exome/paths

echo Filter variants
java -Xmx2g -jar $gatkDir/GenomeAnalysisTK.jar \
  -T VariantFiltration \
  -R $genomeFastaFile \
  --variant $inVcfFile \
  --filterExpression "QD < 2.0" \
  --filterExpression "ReadPosRankSum < -20.0" \
  --filterExpression "InbreedingCoeff < -0.8" \
  --filterExpression "FS > 200.0" \
  --filterName QDFilter \
  --filterName ReadPosFilter \
  --filterName InbreedingFilter \
  --filterName FSFilter \
  -o $outVcfFile
