#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$bamFile" ]
then
  bamFile="$1"
fi
if [ -z "$genomeFastaFile" ]
then
  genomeFastaFile="$2"
fi
if [ -z "$dbSnpVcfFile" ]
then
  dbSnpVcfFile="$3"
fi
if [ -z "$intervalsFile" ]
then
  intervalsFile="$4"
fi

source scripts/exome/paths

gatkXmx=16g
gatkThreads=16

echo Performing Indel realignment on $bamFile
java -Xmx${gatkXmx} -jar $gatkDir/GenomeAnalysisTK.jar \
  -I $bamFile \
  -R $genomeFastaFile \
  -T IndelRealigner \
  -targetIntervals $intervalsFile \
  -known $dbSnpVcfFile \
  -LOD 0.4 \
  -o ${bamFile}.tmp.bam

echo Counting covariates on $bamFile
java -Xmx${gatkXmx} -jar $gatkDir/GenomeAnalysisTK.jar \
  -I ${bamFile}.tmp.bam \
  -R $genomeFastaFile \
  -T CountCovariates \
  -knownSites $dbSnpVcfFile \
  -cov ReadGroupCovariate \
  -cov QualityScoreCovariate \
  -cov CycleCovariate \
  -cov DinucCovariate \
  --num_threads $gatkThreads \
  -recalFile ${bamFile}.recal.csv

echo Recalibrating table for $bamFile
java -Xmx${gatkXmx} -jar $gatkDir/GenomeAnalysisTK.jar \
  -I ${bamFile}.tmp.bam \
  -R $genomeFastaFile \
  -T TableRecalibration \
  -recalFile ${bamFile}.recal.csv \
  -o $bamFile

rm -f ${bamFile/\.bam/.bai}
rm -f ${bamFile}.tmp.*
