#!/bin/bash

source scripts/create_temp_files
source scripts/exome/paths

function buildEntrezGeneFiles {
  tail -n +2 $entrezSeqGeneFile > $tmpFile1
  python2 code/FilterFile.py $tmpFile1 "x[12]=='GRCh37.p5-Primary Assembly'" 0 $tmpFile2
  python2 code/BuildEntrezGenePositionsFile.py $tmpFile2 $entrezGenePositionsFile $entrezGeneStrandFile
#  python2 code/BuildEntrezGeneSequencesFile.py $genomehg19FastaFile $entrezGenePositionsFile $entrezGeneSequencesFile
}

buildEntrezGeneFiles
scripts/exome/parse_common_variant_info

source scripts/delete_temp_files
