#!/bin/bash

source scripts/create_temp_files
source scripts/exome/paths

if [ ! -f $thousandGenomesCommonVariantsFile ]
then
  echo Get thousand genomes variant frequencies
  wget -O $thousandGenomesVariantsFile $thousandGenomesVariantsRemoteFile
  gunzip $thousandGenomesVariantsFile
  python2 code/PrintLinesNotStartingWith.py ${thousandGenomesVariantsFile/\.gz/} "#" > $tmpFile6
  python2 code/InsertColumnViaExpression.py $tmpFile6 "'chr' + x[0] + '__' + x[1]" $tmpFile7
  python2 code/InsertColumnViaExpression.py $tmpFile7 "[y for y in x[7].split(';') if y.startswith('LDAF=')][0].replace('LDAF=', '')" $tmpFile6
  python2 code/SelectColumns.py $tmpFile6 8,9 $thousandGenomesVariantFrequenciesFile
  python2 code/FilterFile.py $thousandGenomesVariantFrequenciesFile "float(x[1]) > 0.01" 0 $tmpFile6
  python2 code/SelectColumns.py $tmpFile6 0 $thousandGenomesCommonVariantsFile
  rm ${thousandGenomesVariantsFile/\.gz/}
fi

if [ ! -f $dbSnpCommonVariantsFile ]
then
  echo Identify common variants
  tail -n +2 $dbSnpUCSCFile > $tmpFile6
  python2 code/InsertColumnViaExpression.py $tmpFile6 "x[0] + '__' + str(int(x[1]) + 1)" $tmpFile7
  python2 code/SelectColumns.py $tmpFile7 3 $dbSnpCommonVariantsFile
fi

source scripts/delete_temp_files
