#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$bamFile" ]
then
  bamFile=$1
fi
if [ -z "$markDuplicates" ]
then
  markDuplicates=$2
fi

function sortFile {
  echo Sorting
  $samToolsDir/samtools sort $bamFile ${bamFile/\.bam/.mod}
  mv ${bamFile/\.bam/.mod.bam} $bamFile

##  java -Xmx16g -jar $picardDir/SortSam.jar INPUT=$bamFile OUTPUT=${bamFile/\.bam/.mod.bam} CREATE_INDEX=true SORT_ORDER=coordinate VALIDATION_STRINGENCY=LENIENT
}

function indexFile {
  echo Indexing
  $samToolsDir/samtools index $bamFile
}

source scripts/exome/paths

sortFile
indexFile

if [ "$markDuplicates" == "TRUE" ]
then
  echo Marking duplicates
  java -Xmx16g -jar $picardDir/MarkDuplicates.jar INPUT=$bamFile OUTPUT=${bamFile/\.bam/.mod.bam} METRICS_FILE=${bamFile/\.bam/_dup_metrics.txt} ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT
  mv ${bamFile/\.bam/.mod.bam} $bamFile

  sortFile
  indexFile
fi
