#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$inVcfFile" ]
then
  inVcfFile="$1"
fi
if [ -z "$outVcfFile" ]
then
  outVcfFile="$2"
fi

source scripts/exome2/paths
source scripts/create_temp_files

currentDir=`pwd`

if [ ! -f $mutationAssessorFile ]
then
  mkdir -p $mutationAssessorDir
  cd $mutationAssessorDir
  wget http://getma.org/MA.scores.hg19.tar.bz2
  tar -zxvf MA.scores.hg19.tar.bz2
  rm MA.scores.hg19.tar.bz2
  cd MA.hg19
  python2 ~/Pipeline/code/ParseMutationAssessor.py "MA*.txt" $mutationAssessorFile
  rm MA*.txt
  cd $currentDir
fi

echo Annotating conservation
python2 code/AnnotateVcf.py $inVcfFile "$dbNSFPDir/dbNSFP2.0b3_variant.chr*" SIFT 0 1 3 21 $tmpFile1
python2 code/AnnotateVcf.py $tmpFile1 "$dbNSFPDir/dbNSFP2.0b3_variant.chr*" Polyphen 0 1 3 22 $tmpFile2
python2 code/AnnotateVcf.py $tmpFile2 $mutationAssessorFile MutAssr 0 1 2 3 $tmpFile1

python2 code/ParsePathogenicityAnnotationsFromVcf.py $tmpFile1 SIFT,Polyphen,MutAssr $tmpFile2

perl /data/Software/condel/bin/was_SPM.pl /data/Software/condel/config/ $tmpFile2 > $tmpFile3

python2 code/InsertColumnViaExpression.py $tmpFile3 "x[0].split('__')[0]" $tmpFile4
python2 code/InsertColumnViaExpression.py $tmpFile4 "x[0].split('__')[1]" $tmpFile3
python2 code/InsertColumnViaExpression.py $tmpFile3 "x[0].split('__')[2]" $tmpFile4
python2 code/SelectColumns.py $tmpFile4 3,4,5,1,2 $tmpFile3

python2 code/AnnotateVcf.py $tmpFile1 $tmpFile3 CondelScore 0 1 2 3 $tmpFile2
python2 code/AnnotateVcf.py $tmpFile2 $tmpFile3 CondelCall 0 1 2 4 $outVcfFile

source scripts/delete_temp_files

############################################################################
# dbNSFP
############################################################################
#1 = chr = 3
#2 = pos(1-coor) = 361487
#3 = ref = C
#4 = alt = G
#5 = aaref = L
#6 = aaalt = V
#7 = hg18_pos(1-coor) = 336487
#8 = genename = CHL1
#9 = Uniprot_acc = B3KX75;O00533;O00533-2
#10 = Uniprot_id = .;CHL1_HUMAN;.
#11 = Uniprot_aapos = 10;10;10
#12 = Interpro_domain = .
#13 = cds_strand = +
#14 = refcodon = CTA
#15 = SLR_test_statistic = .
#16 = codonpos = 1
#17 = fold-degenerate = 2
#18 = Ancestral_allele = C
#19 = Ensembl_geneid = ENSG00000134121
#20 = Ensembl_transcriptid = ENST00000256509;ENST00000397491;ENST00000427688;ENST00000421198;ENST00000435603;ENST00000449294
#21 = aapos = 10
#22 = SIFT_score = 0.620000
#23 = Polyphen2_HDIV_score = 0.009;0.004;0.204
#24 = Polyphen2_HDIV_pred = B;B;B
#25 = Polyphen2_HVAR_score = 0.004;0.007;0.104
#26 = Polyphen2_HVAR_pred = B;B;B
#27 = LRT_score = 0.09560
#28 = LRT_pred = N
#29 = MutationTaster_score = 0.005542
#30 = MutationTaster_pred = N
#31 = GERP++_NR = 4.91
#32 = GERP++_RS = -6.9
#33 = phyloP = -1.642000
#34 = 29way_pi = 0.264:0.3477:0.2037:0.1847
#35 = 29way_logOdds = 1.3608
#36 = LRT_Omega = 1.906350
#37 = UniSNP_ids = .
#38 = 1000Gp1_AC = 2
#39 = 1000GP1_AF = 9.157509157509158E-4
#40 = 1000Gp1_AFR_AC = 0
#41 = 1000Gp1_AFR_AF = 0
#42 = 1000Gp1_EUR_AC = 0.0
#43 = 1000Gp1_EUR_AF = 0
#44 = 1000Gp1_AMR_AC = 0.0
#45 = 1000Gp1_AMR_AF = 2
#46 = 1000Gp1_ASN_AC = 0.0055248618784530384
#47 = 1000Gp1_ASN_AF = 0
#48 = ESP5400_AA_AF = 5.35E-4
#49 = ESP5400_EA_AF = 0.0
#50 = Gene_old_names = .
#51 = Gene_other_names = CALL;L1CAM2;FLJ44930;MGC132578
#52 = Uniprot_acc = O00533
#53 = Uniprot_id = CHL1_HUMAN
#54 = Entrez_gene_id = 10752
#55 = CCDS_id = CCDS2556.1
#56 = Refseq_id = NM_006614;NM_001253387
#57 = ucsc_id = uc003bot.3
#58 = MIM_id = 607416
#59 = Gene_full_name = cell adhesion molecule with homology to L1CAM (close homolog of L1)
#60 = Pathway = .
#61 = Function_description = Extracellular matrix and cell adhesion protein that plays a role in nervous system development and in synaptic plasticity. Both soluble and membranous forms promote neurite outgrowth of cerebellar and hippocampal neurons and suppress neuronal cell death. Plays a role in neuronal positioning of pyramidal neurons and in regulation of both the number of interneurons and the efficacy of GABAergic synapses. May play a role in regulating cell migration in nerve regeneration and cortical development. Potentiates integrin-dependent cell migration towards extracellular matrix proteins. Recruits ANK3 to the plasma membrane (By similarity).
#62 = Disease_description = .
#63 = MIM_phenotype_id = .
#64 = MIM_disease = .
#65 = Trait_association(GWAS) = Sudden cardiac arrest[21658281];Response to antidepressant treatment[22041458];Prostate cancer (gene x gene interaction)[22219177];	unclassifiable (Anatomical System);amygdala;medulla oblongata;ovary;fovea centralis;choroid;lens;skeletal muscle;skin;retina;optic nerve;whole body;lung;frontal lobe;placenta;bone;macula lutea;amniotic fluid;kidney;spinal ganglion;mammary gland;brain;aorta;peripheral nerve;	amygdala;occipital lobe;medulla oblongata;superior cervical ganglion;olfactory bulb;atrioventricular node;subthalamic nucleus;fetal brain;prefrontal cortex;globus pallidus;trigeminal ganglion;cingulate cortex;parietal lobe;
#66 = Expression(egenetics) = E2F1[20195357];JUN[20195357];
#67 = Expression(GNF/Atlas) = .
#68 = Interactions(IntAct) = 0.39224
#69 = Interactions(BioGRID) = 0.09664
#70 = P(HI) = 0.39224
#71 = P(rec) = 0.09664
#72 = Known_rec_info = .
