#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$bamFile" ]
then
  bamFile=$1
fi

source scripts/exome2/paths

echo Filtering BAM
$bamToolsFile filter -mapQuality ">=20" -in $bamFile -out $bamFile.mod
mv $bamFile.mod $bamFile
