#!/bin/bash

fastQCDir=Software/FastQC
samToolsDir=Software/samtools-0.1.18
bamToolsFile=Software/bamtools/bin/bamtools
bwaDir=Software/bwa-0.6.1
gatkDir=Software/GenomeAnalysisTK-2.3-4-g57ea19f
picardDir=Software/picard-tools-1.82
snpEffDir=Software/snpEff_3_1
snpEffBaseCommand="java -jar snpEff.jar"
vcfToolsDir=Software/vcftools_0.1.9/bin2
bamUtilFile=Software/bamUtil_1.0.2/bamUtil/bin/bam

genomehg19Dir=Genomes/hg19_GATK
genomehg19FastaFile=$genomehg19Dir/ucsc.hg19.fasta
genomehg19dbSnpVcfFile=$genomehg19Dir/dbsnp_137.hg19.vcf
genomehg19HapMapVcfFile=$genomehg19Dir/hapmap_3.3.hg19.vcf
genomehg19ThousandGenomesVcfFile=$genomehg19Dir/1000G_omni2.5.hg19.vcf
genomehg19MillsVcfFile=$genomehg19Dir/Mills_and_1000G_gold_standard.indels.hg19.vcf

genomeb37Dir=Genomes/b37
genomeb37FastaFile=$genomeb37Dir/human_g1k_v37.fasta
genomeb37dbSnpVcfFile=$genomeb37Dir/dbsnp_137.b37.vcf
genomeb37HapMapVcfFile=$genomeb37Dir/hapmap_3.3.b37.vcf
genomeb37ThousandGenomesVcfFile=$genomeb37Dir/1000G_omni2.5.b37.vcf
genomeb37MillsVcfFile=$genomeb37Dir/Mills_and_1000G_gold_standard.indels.b37.vcf

function downloadGatkBundleFile {
  revision=$1
  genomeV=$2
  bundleFile=$3
  genomeDir=$4

  if [ ! -f $bundleFile ]
  then
    source scripts/create_temp_files
    bundleFileName=`basename $bundleFile`
    wget --user=gsapubftp-anonymous ftp://ftp.broadinstitute.org/bundle/$revision/$genomeV/$bundleFileName.gz -P $tmpDir
    gunzip $tmpDir/$bundleFileName.gz
    mv $tmpDir/$bundleFileName $genomeDir
    source scripts/delete_temp_files
  fi
}

downloadGatkBundleFile 2.3 hg19 $genomehg19FastaFile $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 $genomehg19FastaFile.fai $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 $genomehg19dbSnpVcfFile $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 ${genomehg19dbSnpVcfFile/\.vcf/.vcf.idx} $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 $genomehg19HapMapVcfFile $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 ${genomehg19HapMapVcfFile/\.vcf/.vcf.idx} $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 $genomehg19ThousandGenomesVcfFile $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 ${genomehg19ThousandGenomesVcfFile/\.vcf/.vcf.idx} $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 $genomehg19MillsVcfFile $genomehg19Dir
downloadGatkBundleFile 2.3 hg19 ${genomehg19MillsVcfFile/\.vcf/.vcf.idx} $genomehg19Dir
downloadGatkBundleFile 2.3 b37 $genomeb37FastaFile $genomeb37Dir
downloadGatkBundleFile 2.3 b37 $genomeb37FastaFile.fai $genomeb37Dir
downloadGatkBundleFile 2.3 b37 $genomeb37dbSnpVcfFile $genomeb37Dir
downloadGatkBundleFile 2.3 b37 ${genomeb37dbSnpVcfFile/\.vcf/.vcf.idx} $genomeb37Dir
downloadGatkBundleFile 2.3 b37 $genomeb37HapMapVcfFile $genomeb37Dir
downloadGatkBundleFile 2.3 b37 ${genomeb37HapMapVcfFile/\.vcf/.vcf.idx} $genomeb37Dir
downloadGatkBundleFile 2.3 b37 $genomeb37ThousandGenomesVcfFile $genomeb37Dir
downloadGatkBundleFile 2.3 b37 ${genomeb37ThousandGenomesVcfFile/\.vcf/.vcf.idx} $genomeb37Dir
downloadGatkBundleFile 2.3 b37 $genomeb37MillsVcfFile $genomeb37Dir
downloadGatkBundleFile 2.3 b37 ${genomeb37MillsVcfFile/\.vcf/.vcf.idx} $genomeb37Dir

thousandGenomesVariantsRemoteDir="ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20110521"
thousandGenomesVariantsRemoteFile="$thousandGenomesVariantsRemoteDir/ALL.wgs.phase1_release_v3.20101123.snps_indels_sv.sites.vcf.gz"
thousandGenomesVariantsFile=library/ALL.wgs.phase1_release_v3.20101123.snps_indels_sv.sites.vcf
thousandGenomesCommonVariantsFile=library/All.wgs.phase1_release_v3.20101123.snps_indels_sv.common.txt

esp6500RemoteFile="http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI.snps_indels.txt.tar.gz"
esp6500VariantsDir=ESP6500
esp6500PackagedFile=$esp6500VariantsDir/ESP6500SI.snps_indels.txt.tar.gz
esp6500CommonVariantsFile=$esp6500VariantsDir/ESP6500SI.common.txt

dbSnpUCSCFile=library/UCSC_hg19.snp135Common.txt
dbSnpCommonVariantsFile=library/hg19.dbSNP.135.commonVariants.txt

ucscCanonicalFile=library/UCSC_hg19_knownCanonical.txt

# From ftp://ftp.ncbi.nih.gov/genomes/H_sapiens/mapview/seq_gene.md
entrezSeqGeneFile=library/Entrez_seq_gene.md
entrezGenePositionsFile=library/Entrez_Gene_Positions.txt
entrezGeneStrandFile=library/Entrez_Gene_Strand.txt
entrezGeneSymbolsFile=library/Entrez_gene_symbols.txt
entrezGeneSequencesFile=library/Entrez_Gene_Sequences.txt
entrezGenehg19BedFile=library/Entrez_Gene_hg19.bed
entrezGeneb37BedFile=library/Entrez_Gene_b37.bed
entrezGenehg19ExonBedFile=library/Entrez_Gene_Exon_Positions_hg19.bed
entrezGenehg19ExonPositionMapFile=library/Entrez_Gene_Exon_Positions_Map_hg19.txt

dbNSFPDir=dbNSFP2

mutationAssessorDir=compute/MutationAssessor
mutationAssessorFile=$mutationAssessorDir/MA.hg19/MutationAssessorValues_hg19.txt
