#!/bin/bash

if [ -n "$PBS_O_WORKDIR" ]
then
  cd "$PBS_O_WORKDIR"
fi

if [ -z "$bamFile" ]
then
  bamFile=$1
fi

source scripts/exome2/paths

echo Sorting $bamFile
$samToolsDir/samtools sort $bamFile ${bamFile/\.bam/.mod}
mv ${bamFile/\.bam/.mod.bam} $bamFile
