#!/bin/bash

cd ML-Flex

function runExperiment {
  java -Xmx4g -jar mlflex.jar ACTION=Reset EXPERIMENTS=${experiment} NUM_THREADS=1
  java -Xmx4g -jar mlflex.jar ACTION=Process EXPERIMENTS=${experiment} NUM_THREADS=1 THREAD_TIMEOUT_MINUTES=5 PAUSE_SECONDS=1 DEBUG=false
}

for i in 1 2
do
  runExperiment utahontario${i}
  runExperiment utahontario${i}_Permute
  runExperiment utahontario${i}_RepeatA
  runExperiment utahontario${i}_BIOCARTA
  runExperiment utahontario${i}_KEGG
  runExperiment utahontario${i}_REACTOME
  runExperiment utahontario${i}_SPathways
done
