#!/bin/bash

###############################################################
# Parse results for 0124vs35
###############################################################

source scripts/create_temp_files

mkdir -p ML-Flex_Results/0124vs35/NoPathways/UtahTraining/Predictions
mkdir -p ML-Flex_Results/0124vs35/NoPathways/OntarioTesting/Predictions
mkdir -p ML-Flex_Results/0124vs35/NoPathways/AllTesting/Predictions
mkdir -p ML-Flex_Results/0124vs35/NoPathways/All/Predictions

python code/FixNewLines.py ML-Flex/Output/utahontario1Experiment/Results/utahontario1_weka_svm_weights_r_svm_rbf_Training_Data_PredictionInfo.txt $tmpFile1
python code/ReplaceText.py $tmpFile1 InstanceID Instance_ID $tmpFile1
python code/ReplaceText.py $tmpFile1 DependentVariableValue Dependent_Variable_Value $tmpFile1
python code/PrefixLinesWith.py $tmpFile1 Utah__ 1 ML-Flex_Results/0124vs35/NoPathways/UtahTraining/Predictions/All

python code/FixNewLines.py ML-Flex/Output/utahontario1Experiment/Results/utahontario1_weka_svm_weights_r_svm_rbf_PredictionInfo.txt $tmpFile1
python code/FixNewLines.py ML-Flex/Output/utahontario2Experiment/Results/utahontario2_weka_svm_weights_r_svm_rbf_PredictionInfo.txt $tmpFile2
tail -n +2 $tmpFile2 > $tmpFile3
cat $tmpFile1 $tmpFile3 > $tmpFile4
python code/ReplaceText.py $tmpFile4 InstanceID Instance_ID $tmpFile4
python code/ReplaceText.py $tmpFile4 DependentVariableValue Dependent_Variable_Value $tmpFile4
python code/PrefixLinesWith.py $tmpFile4 Ontario__ 1 ML-Flex_Results/0124vs35/NoPathways/OntarioTesting/Predictions/All
cp ML-Flex_Results/0124vs35/NoPathways/OntarioTesting/Predictions/All ML-Flex_Results/0124vs35/NoPathways/AllTesting/Predictions/All

python code/HeaderCat2.py ML-Flex_Results/0124vs35/NoPathways/UtahTraining/Predictions/All ML-Flex_Results/0124vs35/NoPathways/OntarioTesting/Predictions/All ML-Flex_Results/0124vs35/NoPathways/All/Predictions/All

cp -v ML-Flex/Output/utahontario1_RepeatAExperiment/*NumFeatures* ML-Flex_Results/0124vs35/NoPathways/UtahTraining/

cp -v ML-Flex/Output/utahontario1Experiment/Results/utahontario1_weka_svm_weights_MeanFeatureRanks.txt ML-Flex_Results/0124vs35/NoPathways/UtahTraining/MeanFeatureRanks.txt

###############################################################
# Parse "no-pathway" results for 1vs35
###############################################################

mkdir -p ML-Flex_Results/1vs35/NoPathways/UtahTraining/Predictions
mkdir -p ML-Flex_Results/1vs35/NoPathways/OntarioTesting/Predictions
mkdir -p ML-Flex_Results/1vs35/NoPathways/AllTesting/Predictions
mkdir -p ML-Flex_Results/1vs35/NoPathways/All/Predictions

python code/FixNewLines.py ML-Flex/Output/utahontario1_1vs35Experiment/Results/utahontario1_weka_svm_weights_r_svm_rbf_Training_Data_PredictionInfo.txt $tmpFile1
python code/ReplaceText.py $tmpFile1 InstanceID Instance_ID $tmpFile1
python code/ReplaceText.py $tmpFile1 DependentVariableValue Dependent_Variable_Value $tmpFile1
python code/PrefixLinesWith.py $tmpFile1 Utah__ 1 ML-Flex_Results/1vs35/NoPathways/UtahTraining/Predictions/All

python code/FixNewLines.py ML-Flex/Output/utahontario1_1vs35Experiment/Results/utahontario1_weka_svm_weights_r_svm_rbf_PredictionInfo.txt $tmpFile1
python code/FixNewLines.py ML-Flex/Output/utahontario2_1vs35Experiment/Results/utahontario2_weka_svm_weights_r_svm_rbf_PredictionInfo.txt $tmpFile2
tail -n +2 $tmpFile2 > $tmpFile3
cat $tmpFile1 $tmpFile3 > $tmpFile4
python code/ReplaceText.py $tmpFile4 InstanceID Instance_ID $tmpFile4
python code/ReplaceText.py $tmpFile4 DependentVariableValue Dependent_Variable_Value $tmpFile4
python code/PrefixLinesWith.py $tmpFile4 Ontario__ 1 ML-Flex_Results/1vs35/NoPathways/OntarioTesting/Predictions/All
cp ML-Flex_Results/1vs35/NoPathways/OntarioTesting/Predictions/All ML-Flex_Results/1vs35/NoPathways/AllTesting/Predictions/All

python code/HeaderCat2.py ML-Flex_Results/1vs35/NoPathways/UtahTraining/Predictions/All ML-Flex_Results/1vs35/NoPathways/OntarioTesting/Predictions/All ML-Flex_Results/1vs35/NoPathways/All/Predictions/All

cp -v ML-Flex/Output/utahontario1_1vs35Experiment/Results/utahontario1_weka_svm_weights_MeanFeatureRanks.txt ML-Flex_Results/1vs35/NoPathways/UtahTraining/MeanFeatureRanks.txt

###############################################################
# Parse results for GSE12517
###############################################################

mkdir -p ML-Flex_Results/GSE12517
cp -v ML-Flex/Output/GSE12517_TamoxifenExperiment/Results/GSE12517_weka_svm_weights_MeanFeatureRanks.txt ML-Flex_Results/GSE12517/Tamoxifen_MeanFeatureRanks.txt
cp -v ML-Flex/Output/GSE12517_AromataseInhibitorExperiment/Results/GSE12517_weka_svm_weights_MeanFeatureRanks.txt ML-Flex_Results/GSE12517/AromataseInhibitor_MeanFeatureRanks.txt

function identifySelectedGenes1 {
  selectedGenesDir=ML-Flex_Results/0124vs35/NoPathways/UtahTraining/SelectedGenes
  mkdir -p $selectedGenesDir
  rm -f $selectedGenesDir/*

  featureRanksFile1=ML-Flex/Output/utahontario1Experiment/Results/utahontario1_weka_svm_weights_MeanFeatureRanks.txt
  featureRanksFile2=ML-Flex/Output/utahontario2Experiment/Results/utahontario2_weka_svm_weights_MeanFeatureRanks.txt

  tail -n +2 $featureRanksFile1 > $tmpFile1
  tail -n +2 $featureRanksFile2 > $tmpFile2
  head -n 125 $tmpFile1 > $tmpFile3
  head -n 225 $tmpFile2 > $tmpFile4
  python code/SelectColumns.py $tmpFile3 0 $selectedGenesDir/utahontario1
  python code/SelectColumns.py $tmpFile4 0 $selectedGenesDir/utahontario2
}

identifySelectedGenes1

function buildGeneStatsFile {
  statsFile=Results/Gene.Expression.Stats.txt

  function calcStats {
    expressionFile=$1
    classesFile=$2
    targetClass=$3
    stat=$4
    outFile=$5

    Rscript --vanilla code/CompareValuesForTwoClasses.R $expressionFile $classesFile $targetClass Control $stat $outFile
  }

  mkdir $tmpDir/Stats
  calcStats matrices/utahontario1.batch.txt clinical/utah.24vs35.txt BRCACancer ttest $tmpDir/Stats/A &
  calcStats matrices/utahontario1.batch.txt clinical/ontario.24vs35.txt BRCACancer ttest $tmpDir/Stats/B &
  calcStats matrices/utahontario2.batch.txt clinical/ontario.24vs35.txt BRCACancer ttest $tmpDir/Stats/C &
  calcStats matrices/utahontario1.batch.txt clinical/utah.24vs35.txt BRCACancer fc $tmpDir/Stats/D &
  calcStats matrices/utahontario1.batch.txt clinical/ontario.24vs35.txt BRCACancer fc $tmpDir/Stats/E &
  calcStats matrices/utahontario2.batch.txt clinical/ontario.24vs35.txt BRCACancer fc $tmpDir/Stats/F &
  calcStats matrices/utahontario1.batch.txt clinical/utah.0124vs35.txt BRCACancer ttest $tmpDir/Stats/G &
  calcStats matrices/utahontario1.batch.txt clinical/ontario.0124vs35.txt BRCACancer ttest $tmpDir/Stats/H &
  calcStats matrices/utahontario2.batch.txt clinical/ontario.0124vs35.txt BRCACancer ttest $tmpDir/Stats/I &
  calcStats matrices/utahontario1.batch.txt clinical/utah.0124vs35.txt BRCACancer fc $tmpDir/Stats/J &
  calcStats matrices/utahontario1.batch.txt clinical/ontario.0124vs35.txt BRCACancer fc $tmpDir/Stats/K &
  calcStats matrices/utahontario2.batch.txt clinical/ontario.0124vs35.txt BRCACancer fc $tmpDir/Stats/L &
  calcStats matrices/Visvader.txt clinical/Visvader.Control_vs_BRCA.classes.txt BRCA ttest $tmpDir/Stats/M &
  calcStats matrices/Visvader.txt clinical/Visvader.Control_vs_BRCA.classes.txt BRCA fc $tmpDir/Stats/N &
  wait

  function mergeStats {
    if [ ! -f $statsFile ]
    then
      cp $1 $statsFile
    else
      python code/Join.py $statsFile $1 0 0 NA $statsFile True
    fi
  }

  rm -f $statsFile
  for x in {A..P}
  do
    echo Merging $x
    mergeStats $tmpDir/Stats/$x
  done

  python code/AddDescriptionColumn.py $statsFile library/Entrez_gene_symbols.txt "[No Symbol]"
  python code/AddDescriptionColumn.py $statsFile library/Entrez_gene_names.txt "[No Name]"

  python code/SelectColumns.py $statsFile 0,-2,-1,1to-3 $tmpFile1
  echo -e "Entrez Gene ID\tGene Symbol\tGene Name\tUtah t-test 24vs35\tOntario1 t-test 24vs35\tOntario2 t-test 24vs35\tUtah Fold Change 24vs35\tOntario1 Fold Change 24vs35\tOntario2 Fold Change 24vs35\tUtah t-test 0124vs35\tOntario1 t-test 0124vs35\tOntario2 t-test 0124vs35\tUtah Fold Change 0124vs35\tOntario1 Fold Change 0124vs35\tOntario2 Fold Change 0124vs35\tVisvader t-test\tVisvader Fold Change" > $tmpFile2
  cat $tmpFile2 $tmpFile1 > $statsFile
}

buildGeneStatsFile

function consensusGenes {
  comparison=$1
  ttIndex1=$2
  ttIndex2=$3
  ttIndex3=$4
  fcIndex1=$5
  fcIndex2=$6
  fcIndex3=$7

  statsFile=Results/Gene.Expression.Stats.txt
  consensusGenesFile=Results/Consensus.Genes.$comparison.txt
  consensusGenesIDFile=Results/Consensus.Genes.ID.$comparison.txt

  # Keep only genes that are expressed in the same direction across all three cohorts
  python code/FilterFile.py $statsFile "x[$fcIndex1] != 'NA' and x[$fcIndex2] != 'NA' and x[$fcIndex3] != 'NA' and ((float(x[$fcIndex1])>1.0 and float(x[$fcIndex2])>1.0 and float(x[$fcIndex3])>1.0) or (float(x[$fcIndex1])<1.0 and float(x[$fcIndex2])<1.0 and float(x[$fcIndex3])<1.0))" 1 $tmpFile1
  python code/SelectColumns.py $tmpFile1 0to14 $tmpFile2

  # Add absolute fold change columns
  python code/InsertMatrixColumnViaExpression.py $tmpFile2 "Utah Abs Fold Change" "math.fabs(float(x[$fcIndex1]) - 1)" $tmpFile2
  python code/InsertMatrixColumnViaExpression.py $tmpFile2 "Ontario1 Abs Fold Change" "math.fabs(float(x[$fcIndex2]) - 1)" $tmpFile2
  python code/InsertMatrixColumnViaExpression.py $tmpFile2 "Ontario2 Abs Fold Change" "math.fabs(float(x[$fcIndex3]) - 1)" $tmpFile2

  # Add rank columns
  python code/InsertRankColumn.py $tmpFile2 True $ttIndex1 False $tmpFile2
  python code/InsertRankColumn.py $tmpFile2 True $ttIndex2 False $tmpFile2
  python code/InsertRankColumn.py $tmpFile2 True $ttIndex3 False $tmpFile2
  python code/InsertRankColumn.py $tmpFile2 True 15 True $tmpFile2
  python code/InsertRankColumn.py $tmpFile2 True 16 True $tmpFile2
  python code/InsertRankColumn.py $tmpFile2 True 17 True $tmpFile2

  python code/SortFileByExpression.py $tmpFile2 "utilities.calculateMean([float(y) for y in x[18:]])" forward 1 $tmpFile1

  # Finalize consensus file
  python code/SelectColumns.py $tmpFile1 0to2 $consensusGenesFile
  python code/SelectColumns.py $consensusGenesFile 0 $tmpFile1
  tail -n +2 $tmpFile1 > $consensusGenesIDFile
}

consensusGenes 24v35 3 4 5 6 7 8
consensusGenes 0124v35 9 10 11 12 13 14

python code/FilterFile.py Results/Gene.Expression.Stats.txt "x[12] != 'NA' and x[13] != 'NA' and x[14] != 'NA'" 1 $tmpFile2
python code/InsertRankColumn.py $tmpFile2 True 12 True $tmpFile2
python code/InsertRankColumn.py $tmpFile2 True 13 True $tmpFile2
python code/InsertRankColumn.py $tmpFile2 True 14 True $tmpFile2
python code/SortFileByExpression.py $tmpFile2 "utilities.calculateMean([float(y) for y in x[19:]])" forward 1 $tmpFile1
python code/SelectColumns.py $tmpFile1 0 $tmpFile2
tail -n +2 $tmpFile2 > $tmpFile1
head -n 250 $tmpFile1 > Results/BCSP.Up.Gene.ID.0124vs35.txt
python code/CreateGmtFileFromIDs.py Results/BCSP.Up.Gene.ID.0124vs35.txt Results/BCSP.Up.0124vs35.gmt

# Create expression file that includes all samples
python code/SelectColumns.py clinical/classes.0124vs35.txt 0 $tmpFile2
python code/TransposeData.py matrices/utahontario1.batch.txt $tmpFile3
python code/FilterFileByColumnValues.py $tmpFile3 0 $tmpFile2 1 $tmpFile4
python code/TransposeData.py $tmpFile4 $tmpFile5
python code/SelectColumns.py clinical/ontario.0124vs35.txt 0 $tmpFile2
python code/TransposeData.py matrices/utahontario2.batch.txt $tmpFile3
python code/FilterFileByColumnValues.py $tmpFile3 0 $tmpFile2 1 $tmpFile4
python code/TransposeData.py $tmpFile4 $tmpFile6
python code/MergeMatrixOnRowNames.py $tmpFile5 $tmpFile6 matrices/utahontario.batch.txt
python code/PrintMatrixDimensions.py matrices/utahontario.batch.txt
