#!/bin/bash

source scripts/create_temp_files

predictionsFile=$1
targetClass=$2

aucFile=${predictionsFile/Predictions/AUCs}
permutedAucFile=${predictionsFile/Predictions/PermutedAUCs}

echo $predictionsFile

if [ ! -f $permutedAucFile ]
then
  mkdir -p `dirname $aucFile` `dirname $permutedAucFile`
  Rscript --vanilla code/CalculatePredictionMetrics.R $predictionsFile $targetClass 1000 $aucFile $permutedAucFile
fi
