#!/bin/bash

source scripts/exome2/paths

currentDir=`pwd`
dataDir=compute/BCSP_Exome2
outputDir=$dataDir/Output
sampleMapFile=misc/BCSP_Exome_Sample_Map.txt
tcgaOutputDir=compute/TCGA/Breast/DNA/Germline/Output
gmtFiles=library/all_pathways.gmt
entrezGenesFile=$outputDir/EntrezGenes.txt

source scripts/create_temp_files

#scripts/exome/parse_meta_files
#python2 code/SelectColumns.py $entrezGenePositionsFile 0 $entrezGenesFile

controlSamplesFile=$outputDir/ControlSamples.txt
cancerSamplesFile=$outputDir/CancerSamples.txt

#python2 code/FilterFile.py $sampleMapFile "x[2] in ('2','4')" 0 $tmpFile1
#python2 code/FilterFile.py $sampleMapFile "x[2] in ('3','5')" 0 $tmpFile2
#python2 code/SelectColumns.py $tmpFile1 3 $controlSamplesFile
#python2 code/SelectColumns.py $tmpFile2 3 $cancerSamplesFile

# Find samples that need to be processed
#for f in $dataDir/8929X*_1.txt
#do
#  echo `basename ${f/_1.txt/}` >> $tmpFile15
#done
#cat $tmpFile15 | parallel --max-procs 6 scripts/exome2/fastq_to_bam $dataDir $outputDir {} txt

#ls $outputDir/*.bam | parallel --max-procs 6 scripts/exome2/gatk_pre {} $genomehg19FastaFile $genomehg19dbSnpVcfFile $entrezGenehg19BedFile {.}.reduced {.}.out

#for f in $outputDir/*reduced
#do
#  mv $f $f.bam
#done

#for f in $outputDir/*.bam
#do
#  scripts/exome2/calcstats $f $genomehg19FastaFile
#done

#scripts/exome2/gatk_callvariants "$outputDir/*reduced.bam" $genomehg19FastaFile $genomehg19dbSnpVcfFile SNP $entrezGenehg19BedFile 16 $outputDir/snps.vcf $outputDir/gatk_callsnps.out &
#scripts/exome2/gatk_callvariants "$outputDir/*reduced.bam" $genomehg19FastaFile $genomehg19dbSnpVcfFile INDEL $entrezGenehg19BedFile 16 $outputDir/indels.vcf $outputDir/gatk_callindels.out &
#wait

#scripts/exome2/gatk_filtersnps $outputDir/snps.vcf $genomehg19FastaFile $genomehg19dbSnpVcfFile $genomehg19HapMapVcfFile $genomehg19ThousandGenomesVcfFile $outputDir/snps.filtered.vcf $outputDir/gatk_filtersnps.out
#scripts/exome2/gatk_filterindels $outputDir/indels.vcf $genomehg19FastaFile $genomehg19MillsVcfFile $outputDir/indels.filtered.vcf $outputDir/gatk_filterindels.out

#scripts/exome2/annotate_function $outputDir/snps.filtered.vcf hg19 TRUE $outputDir/snps.annotated.function.vcf
#scripts/exome2/annotate_function $outputDir/indels.filtered.vcf hg19 TRUE $outputDir/indels.annotated.vcf
#scripts/exome2/annotate_function $outputDir/snps.filtered.vcf hg19 FALSE $outputDir/snps.annotated.function.all.vcf
#scripts/exome2/annotate_function $outputDir/indels.filtered.vcf hg19 FALSE $outputDir/indels.annotated.all.vcf

#scripts/exome2/annotate_conservation $outputDir/snps.annotated.function.vcf $outputDir/snps.annotated.vcf
#scripts/exome2/annotate_conservation $outputDir/snps.annotated.function.all.vcf $outputDir/snps.annotated.all.vcf

#python2 code/CalculateVariantFrequencies.py $outputDir/snps.annotated.all.vcf $outputDir/SNP.Frequencies.txt $outputDir/SNP.All.Summary.txt
#python2 code/CalculateVariantFrequencies.py $outputDir/indels.annotated.all.vcf $outputDir/INDEL.Frequencies.txt $outputDir/INDEL.All.Summary.txt
#python2 code/FilterFile.py $outputDir/SNP.Frequencies.txt "float(x[1]) == 0.0 or float(x[1]) > 0.15" 0 $tmpFile1
#python2 code/SelectColumns.py $tmpFile1 0 $outputDir/SNP.Common.txt
#python2 code/FilterFile.py $outputDir/INDEL.Frequencies.txt "float(x[1]) == 0.0 or float(x[1]) > 0.15" 0 $tmpFile1
#python2 code/SelectColumns.py $tmpFile1 0 $outputDir/INDEL.Common.txt

#scripts/exome2/filter_vcf $outputDir/snps.annotated.all.vcf $thousandGenomesCommonVariantsFile $outputDir/snps.annotated.all.filtered.1kG.vcf
#scripts/exome2/filter_vcf $outputDir/snps.annotated.all.filtered.1kG.vcf $esp6500CommonVariantsFile $outputDir/snps.annotated.all.filtered.ESP.vcf
#scripts/exome2/filter_vcf $outputDir/snps.annotated.all.filtered.ESP.vcf $tcgaOutputDir/SNP.Common.txt $outputDir/snps.annotated.all.filtered.TCGA.vcf
#scripts/exome2/filter_vcf $outputDir/snps.annotated.all.filtered.TCGA.vcf $outputDir/SNP.Common.txt $outputDir/snps.annotated.all.filtered.vcf
#scripts/exome2/filter_vcf $outputDir/indels.annotated.all.vcf $thousandGenomesCommonVariantsFile $outputDir/indels.annotated.all.filtered.1kG.vcf
#scripts/exome2/filter_vcf $outputDir/indels.annotated.all.filtered.1kG.vcf $esp6500CommonVariantsFile $outputDir/indels.annotated.all.filtered.ESP.vcf
#scripts/exome2/filter_vcf $outputDir/indels.annotated.all.filtered.ESP.vcf $tcgaOutputDir/INDEL.Common.txt $outputDir/indels.annotated.all.filtered.TCGA.vcf
#scripts/exome2/filter_vcf $outputDir/indels.annotated.all.filtered.TCGA.vcf $outputDir/INDEL.Common.txt $outputDir/indels.annotated.all.filtered.vcf

## Number of variants after all GATK processing
#python2 code/PrintLinesNotStartingWith.py $outputDir/snps.filtered.vcf "#" | wc -l
#python2 code/PrintLinesNotStartingWith.py $outputDir/indels.filtered.vcf "#" | wc -l
##830317
##111190

## Number of variants before TCGA filtering
#python2 code/PrintLinesNotStartingWith.py $outputDir/snps.annotated.all.filtered.ESP.vcf "#" | wc -l
#python2 code/PrintLinesNotStartingWith.py $outputDir/indels.annotated.all.filtered.ESP.vcf "#" | wc -l
##64557
##63095

## Number of variants after TCGA filtering
#python2 code/PrintLinesNotStartingWith.py $outputDir/snps.annotated.all.filtered.TCGA.vcf "#" | wc -l
#python2 code/PrintLinesNotStartingWith.py $outputDir/indels.annotated.all.filtered.TCGA.vcf "#" | wc -l
##56956 (11.8%)
##14642 (76.8%)

## Number of variants after local filtering
#python2 code/PrintLinesNotStartingWith.py $outputDir/snps.annotated.all.filtered.vcf "#" | wc -l
#python2 code/PrintLinesNotStartingWith.py $outputDir/indels.annotated.all.filtered.vcf "#" | wc -l
##52678 (7.5%)
##5830 (60.2%)

#python2 code/AnnotateVcfWithGenesPathways.py $outputDir/snps.annotated.all.filtered.vcf $entrezGenePositionsFile $entrezGeneSymbolsFile $entrezGeneStrandFile $gmtFiles,genesets/BRCA_Genes.gmt $outputDir/SNPs.InExons.bed $outputDir/SNPs.NotInExons.bed $outputDir/snps.final.vcf
#python2 code/AnnotateVcfWithGenesPathways.py $outputDir/indels.annotated.all.filtered.vcf $entrezGenePositionsFile $entrezGeneSymbolsFile $entrezGeneStrandFile $gmtFiles,genesets/BRCA_Genes.gmt $outputDir/INDELs.InExons.bed $outputDir/INDELs.NotInExons.bed $outputDir/indels.final.vcf
#python2 code/ConvertVcfToVariants.py $outputDir/snps.final.vcf,$outputDir/indels.final.vcf MODERATE,HIGH $outputDir/Variants.txt $outputDir/Final.Summary.txt

#python2 code/ReplaceIDs.py $outputDir/Variants.txt $sampleMapFile $outputDir/Variants.txt

#python2 code/SelectColumns.py $entrezGenePositionsFile 0 $tmpFile9
#python2 code/CountMutatedSamples.py $outputDir/Variants.txt $tmpFile9 None $gmtFiles $entrezGeneSymbolsFile None All None $outputDir/Gene.MutFreq.txt $outputDir/Pathway.MutFreq.txt

## Number of genes and pathways with at least one variant before gene-level filtering
#python2 code/PrintVariantStats.py $outputDir/Variants.txt | tee $outputDir/VariantStats.txt

threshold=0.018
#python2 code/FilterFile.py $tcgaOutputDir/Gene.MutFreq.txt "float(x[-1]) < $threshold or x[0] in ('672', '675')" 1 $tmpFile3
#python2 code/SelectColumns.py $tmpFile3 0 $tmpFile4
#tail -n +2 $tmpFile4 > $tmpFile3
#python2 code/Uniquify.py $tmpFile3
#python2 code/FilterFileByColumnValues.py $outputDir/Variants.txt 6 $tmpFile3 1 $outputDir/Variants_Minus_TCGA_Genes.txt

#scripts/exome2/calculate_mutfreq_stats $outputDir/Variants_Minus_TCGA_Genes.txt $entrezGenesFile $entrezGeneSymbolsFile $gmtFiles $controlSamplesFile $cancerSamplesFile UtahControl UtahCancer $outputDir/Gene.MutFreq.Stats.txt $outputDir/Pathway.MutFreq.Stats.txt False

## Number of genes and pathways with at least one variant after gene-level filtering
#python2 code/PrintVariantStats.py $outputDir/Variants_Minus_TCGA_Genes.txt | tee $outputDir/VariantStats_Minus_TCGA_Genes.txt

python2 code/CreateProteinEffectReports.py $outputDir/Variants_Minus_TCGA_Genes.txt $entrezGenePositionsFile $entrezGeneSequencesFile $outputDir/Proteins.txt $outputDir/Protein_Summary.txt

source scripts/delete_temp_files
