#!/bin/bash

buildDir=builddir

rm -rf $buildDir
mkdir -p $buildDir/lib
mkdir -p $buildDir/src/mlflex/tcga
mkdir -p $buildDir/src/mlflex/ucimachinelearning

cp Guts/Java/*.java $buildDir/src/mlflex/
cp Guts/Java/tcga/*.java $buildDir/src/mlflex/tcga/
cp Guts/Java/ucimachinelearning/*.java $buildDir/src/mlflex/ucimachinelearning/
cp Guts/lib/*.jar $buildDir/lib
cp Guts/build.xml $buildDir

cd $buildDir

find src -name *.java > sources_list.txt
javac -Djava.ext.dirs=lib @sources_list.txt

mkdir docs
javadoc -protected -splitindex -author -version -nodeprecated -extdirs lib -d docs @sources_list.txt -sourcepath src

rm sources_list.txt

ant

rm build.xml

cp mlflex.jar ../
cp -r docs ../Java/
cp -r lib ../

cd ..
rm -rf $buildDir
rm -rf src
